# Generated by Django 2.1.5 on 2020-05-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200523_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bill',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
