# Generated by Django 2.1.5 on 2020-05-24 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_submittedorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedorder',
            name='status',
            field=models.CharField(default='working on it', max_length=64),
        ),
    ]
