# Generated by Django 2.1.5 on 2020-05-24 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_submittedorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittedorder',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Order'),
        ),
    ]
