# Generated by Django 2.1.5 on 2020-05-25 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20200524_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomisedSteak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steaks', to='orders.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Steak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side_num', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Steakside',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='submittedorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order'),
        ),
        migrations.AlterField(
            model_name='submittedorder',
            name='status',
            field=models.CharField(default='Working on it', max_length=64),
        ),
        migrations.AddField(
            model_name='customisedsteak',
            name='sides',
            field=models.ManyToManyField(blank=True, to='orders.Steakside'),
        ),
        migrations.AddField(
            model_name='customisedsteak',
            name='steak_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Steak'),
        ),
    ]
