# Generated by Django 2.1.5 on 2020-05-25 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20200525_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='steak',
            name='size',
            field=models.CharField(default='s', max_length=2),
        ),
    ]
