# Generated by Django 2.1.5 on 2020-05-25 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_steak_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steak',
            name='size',
            field=models.CharField(max_length=2),
        ),
    ]
