# Generated by Django 2.1.5 on 2020-05-25 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20200525_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittedorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submittedorders', to='orders.Order'),
        ),
    ]
