# Generated by Django 2.1.5 on 2020-05-25 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20200525_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='customisedsteak',
            name='done',
            field=models.CharField(default='done', max_length=64),
        ),
    ]
