# Generated by Django 2.1.5 on 2020-05-25 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_pasta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasta',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pastas', to='orders.Order'),
        ),
    ]
