# Generated by Django 2.1.5 on 2020-05-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20200525_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pasta',
            name='order',
        ),
        migrations.AddField(
            model_name='pasta',
            name='order',
            field=models.ManyToManyField(blank=True, related_name='pastas', to='orders.Order'),
        ),
    ]
